/* This program is a part of RW mudlib 
 * See /doc/help/copyright for more info
 -----------------------------------------
 * File   : condition.h
 * Author : ¥Ñ creator ²£¥Í
 * Date   : 
 * Note   : Include File.
 * Update :
 *  o 2005-00-00
 *
 -----------------------------------------
 */

#define AIR_CONDITIONER                          "/std/module/condition/air_conditioner"
#define ATTACKDEFEND                             "/std/module/condition/attackdefend"
#define AUDIO                                    "/std/module/condition/audio"
#define BATTLEFIELD_EXPERIENCE                   "/std/module/condition/battlefield_experience"
#define BATTLEFIELD_FEAR                         "/std/module/condition/battlefield_fear"
#define BATTLEFIELD_GLORY                        "/std/module/condition/battlefield_glory"
#define BATTLEFIELD_MURDERER                     "/std/module/condition/battlefield_murderer"
#define BATTLEFIELD_PLAYER_1                     "/std/module/condition/battlefield_player_1"
#define BOSS_HUNTER                              "/std/module/condition/boss_hunter"
#define CHEER_COFFEE                             "/std/module/condition/cheer_coffee"
#define CHRISTMAS_2007                           "/std/module/condition/christmas_2007"
#define CITY_STAMINA                             "/std/module/condition/city_stamina"
#define DEADLY_CONTRACT                          "/std/module/condition/deadly_contract"
#define DIE                                      "/std/module/condition/die"
#define DIGNOSE                                  "/std/module/condition/dignose"
#define EXTREME_SILENCE                          "/std/module/condition/extreme_silence"
#define FINANCEKNOWLEDGE                         "/std/module/condition/financeknowledge"
#define FISHINGNOTE                              "/std/module/condition/fishingnote"
#define FLUTE_WEAK                               "/std/module/condition/flute_weak"
#define GIBAMAN                                  "/std/module/condition/gibaman"
#define GODS_TRANSFORMER                         "/std/module/condition/gods_transformer"
#define GUITAR_WEAK                              "/std/module/condition/guitar_weak"
#define HONOR                                    "/std/module/condition/honor"
#define INVINCIBILITY                            "/std/module/condition/invincibility"
#define KNOWLEDGEBLESS                           "/std/module/condition/knowledgebless"
#define KNOWLEDGESANCTUARY                       "/std/module/condition/knowledgesanctuary"
#define LIFE_MIRACLE                             "/std/module/condition/life_miracle"
#define LOST_AGILITY                             "/std/module/condition/lost_agility"
#define LOST_CHARISMA                            "/std/module/condition/lost_charisma"
#define LOST_ENERGY                              "/std/module/condition/lost_energy"
#define LOST_HEALTH                              "/std/module/condition/lost_health"
#define LOST_INTELLIGENCE                        "/std/module/condition/lost_intelligence"
#define LOST_PHYSIQUE                            "/std/module/condition/lost_physique"
#define LOST_STAMINA                             "/std/module/condition/lost_stamina"
#define LOST_STRENGTH                            "/std/module/condition/lost_strength"
#define LOSTLAND                                 "/std/module/condition/lostland"
#define LOSTSEAL                                 "/std/module/condition/lostseal"
#define MAGNETIC_STONE                           "/std/module/condition/magnetic_stone"
#define MEDICATED_WINE                           "/std/module/condition/medicated_wine"
#define MILK                                     "/std/module/condition/milk"
#define MOONCAKE_2007                            "/std/module/condition/mooncake_2007"
#define NEWBIE                                   "/std/module/condition/newbie"
#define NEWBIE_ADV                               "/std/module/condition/newbie_adv"
#define PEANUT_GLUE_PUDDING                      "/std/module/condition/peanut_glue_pudding"
#define PERFUME_HERB                             "/std/module/condition/perfume_herb"
#define PERFUME_HERBAGE                          "/std/module/condition/perfume_herbage"
#define PERFUME_LILY                             "/std/module/condition/perfume_lily"
#define PERFUME_ROSE                             "/std/module/condition/perfume_rose"
#define PERFUME_SUNFLOWER                        "/std/module/condition/perfume_sunflower"
#define POISON_GIANT_SPIDER                      "/std/module/condition/poison_giant_spider"
#define POWER_AGILITY                            "/std/module/condition/power_agility"
#define POWER_CHARISMA                           "/std/module/condition/power_charisma"
#define POWER_INTELLIGENCE                       "/std/module/condition/power_intelligence"
#define POWER_PHYSIQUE                           "/std/module/condition/power_physique"
#define POWER_STRENGTH                           "/std/module/condition/power_strength"
#define RADIATION                                "/std/module/condition/radiation"
#define SEEHUMANS                                "/std/module/condition/seehumans"
#define SELFCHARGE                               "/std/module/condition/selfcharge"
#define SESAME_GLUE_PUDDING                      "/std/module/condition/sesame_glue_pudding"
#define SIGHTSEEBLESS                            "/std/module/condition/sightseebless"
#define SIGHTSEEBLESS_ADV1                       "/std/module/condition/sightseebless_adv1"
#define SIGHTSEEBLESS_ADV2                       "/std/module/condition/sightseebless_adv2"
#define SIGHTSEEBLESS_ADV3                       "/std/module/condition/sightseebless_adv3"
#define SIGHTSEEBLESS_ADV4                       "/std/module/condition/sightseebless_adv4"
#define SIGHTSEEBLESS_ADV5                       "/std/module/condition/sightseebless_adv5"
#define SIGHTSEEBLESS_ADV6                       "/std/module/condition/sightseebless_adv6"
#define SIGHTSEEBLESS_ADV7                       "/std/module/condition/sightseebless_adv7"
#define SKY_1ST_STATUE                           "/std/module/condition/sky_1st_statue"
#define SKY_2ND_STATUE                           "/std/module/condition/sky_2nd_statue"
#define SKY_3RD_STATUE                           "/std/module/condition/sky_3rd_statue"
#define STEAMED_ROLL_HEAL                        "/std/module/condition/steamed_roll_heal"
#define TELEVISION                               "/std/module/condition/television"
#define WHISKEY                                  "/std/module/condition/whiskey"

